POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YWNrIiwiaWQiOiI2MjE2NDA1OTU5NjgwOTA0NTE2ZWY4MzQiLCJpYXQiOjE2NDU2Mjk0OTcsImV4cCI6MTY0NTYzMzA5N30.9E3CsW_C9jB64tJxbzFLhhTFyVsu6FGdc5uaihhIh74

{
    "author": "Aku Ankka",
    "title": "butter factory times",
    "url": "www.butter.quack",
    "likes": 313
}